project_id = "izqdyzqkglcmyzmfsrmt"

[functions.paystack-initialize]
verify_jwt = true

[functions.paystack-verify]
verify_jwt = false

[functions.send-booking-notification]
verify_jwt = true

[functions.email-tracking]
verify_jwt = false

[functions.ai-package-recommender]
verify_jwt = true
